---	
- name: Intro to Ansible Playbooks
  hosts: prod 
  gather_facts: no
  become: yes

  tasks:

    - name: Ensure group "somegroup" exists
      ansible.builtin.group:
        name: "{{ server_group.name }}"
        state: "{{ server_group.state }}"

    - name: Add users
      ansible.builtin.user:
        name: "{{ item.name}}"
        comment: "{{ item.comment}}"
        group: "{{ item.group}}"
      loop: "{{ server_users }}"