---	
- name: Reboots all servers
  hosts: group_ubuntu,group_rockylinux
  gather_facts: yes
  become: yes

  tasks:

    - debug:
        var: ansible_facts.os_family

    - name: Install the latest version of Apache
      ansible.builtin.yum:
        name: httpd
        state: latest
      when: ansible_facts.os_family == "RedHat"

    - name: Install apache httpd  (state=present is optional)
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_facts.os_family == "Debian"