---	
- name: Reboots all servers
  hosts: group_rockylinux
  gather_facts: yes
  become: yes

  tasks:

    - debug:
        var: ansible_facts.os_family

    - name: Install the latest version of Apache
      ansible.builtin.yum:
        name: httpd
        state: latest
      register: redhat_output
      when: ansible_facts.os_family == "RedHat"

    # - name: Install apache httpd  (state=present is optional)
    #   ansible.builtin.apt:
    #     name: apache2
    #     state: present
    #     update_cache: yes
    #   when: ansible_facts.os_family == "Debian"

    - debug:
        var: redhat_output.failed
  

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: httpd
        state: started
      when: redhat_output.failed == true

  

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: firewalld
        state: stopped
      when: redhat_output.failed == true






  